spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driverClassName: org.h2.Driver
    password: ''
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: '6379'

redis_key: keyword

refresh:
  db:
    schedule:
      millisecond: '3000'

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState : 10000
    instances:
      blog:
        baseConfig: default